from django.conf.urls.defaults import *

urlpatterns = patterns('review.views',
    (r'^$', 'dashboard'),
    (r'^stats/', 'stats'),
    (r'^new_comment/', 'new_comment'),
    (r'^change_task/', 'change_task'),
    (r'^reply/', 'reply'),
    (r'^delete_comment/', 'delete_comment'),
    (r'^edit_comment/', 'edit_comment'),
    (r'^vote/', 'vote'),
    (r'^unvote/', 'unvote'),
    (r'^user/(?P<username>\w+)/edit', 'edit_profile'),
    (r'^user/(?P<username>\w+)', 'summary'),
    (r'^allusers/', 'allusers'),
    (r'activity/(?P<review_milestone_id>\d+)/(?P<username>\w+)', 'all_activity'),
    (r'^request_extension/(?P<milestone_id>\d+)', 'request_extension'),
    (r'^review_milestone_info/(?P<review_milestone_id>\d+)', 'review_milestone_info'),
    (r'^dashboard/(?P<username>\w+)', 'student_dashboard'),
    (r'^manage', 'manage'),
    (r'^cancel_assignment', 'cancel_assignment'),
    (r'^more_work', 'more_work'),
    (r'^search', 'search'),
)
