from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView
import django.contrib.auth.views
import review.views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='dashboard')),
    url(r'^dashboard/(?P<username>\w+)', review.views.student_dashboard),
    url(r'^dashboard/', review.views.dashboard),
    url(r'^more_work/', review.views.more_work),
    url(r'^cancel_assignment/', review.views.cancel_assignment),
    url(r'^view/(?P<chunk_id>\d+)', review.views.view_chunk),
    url(r'^submission/(?P<viewtype>(all|code))/(?P<submission_id>\d+)', review.views.view_all_chunks),
    url(r'^submission-for-milestone/(?P<viewtype>(all|code))/(?P<milestone_id>\d+)/(?P<username>\w+)', review.views.view_submission_for_milestone),
    url(r'^simulate/(?P<review_milestone_id>\d+)', review.views.simulate),
    url(r'^list_users/(?P<review_milestone_id>\d+)', review.views.list_users),
    url(r'^load_similar_comments/(?P<chunk_id>\d+)/(?P<load_all_staff_comments>(True|False))', review.views.load_similar_comments),
    url(r'^highlight_comment_chunk_line/(?P<comment_id>\d+)', review.views.highlight_comment_chunk_line),
    url(r'^change_task/', review.views.change_task),
    url(r'^new_comment/', review.views.new_comment),
    url(r'^reply/', review.views.reply),
    url(r'^delete_comment/', review.views.delete_comment),
    url(r'^edit_comment/', review.views.edit_comment),
    url(r'^vote/', review.views.vote),
    url(r'^unvote/', review.views.unvote),
    url(r'activity/(?P<review_milestone_id>\d+)/(?P<username>\w+)', review.views.all_activity),
    url(r'^search/', review.views.search),
    url(r'login/', django.contrib.auth.views.login, {
        'template_name': 'login.html',
    }),
    url(r'logout/', django.contrib.auth.views.logout),
    url(r'register/(?P<email>.+alum\.mit\.edu)/(?P<code>[0-9A-Fa-f]+$)', review.views.register),
    url(r'reputation_adj/', review.views.reputation_adjustment),
    url(r'register/', review.views.invalid_registration),
    url(r'^reset/$', django.contrib.auth.views.password_reset,
                  {'template_name': 'reset.html'}),
    url(r'^reset/done/$', django.contrib.auth.views.password_reset_done,
                      {'template_name': 'reset_done.html'}),
    url(r'^reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
            django.contrib.auth.views.password_reset_confirm,
            {'template_name': 'reset_confirm.html'}),
    url(r'^reset/complete/$', django.contrib.auth.views.password_reset_complete,
                           {'template_name': 'reset_complete.html'}),
    url(r'registration/$', review.views.registration_request),
    url(r'^registration/complete/$', TemplateView.as_view(template_name='registration_request_complete.html')),
    url(r'^enroll/', review.views.edit_membership),
    url(r'bulk_add/', review.views.bulk_add),
    url(r'^user/(?P<username>\w+)/edit', review.views.edit_profile),
    url(r'^user/(?P<username>\w+)', review.views.view_profile),
    url(r'^request_extension/(?P<milestone_id>\d+)', review.views.request_extension),
    url(r'^allusers/', review.views.allusers),
    url(r'^manage/', review.views.manage),
    url(r'^all_extensions/(?P<milestone_id>\d+)', review.views.all_extensions),
]
