# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='alum_count_default',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='alums',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='alums_default',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='staff_count_default',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='staff_default',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='student_count_default',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='students',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='students_default',
        ),
    ]
