# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20160904_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
