# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20160904_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmilestone',
            old_name='chunks_to_assign',
            new_name='chunk_priorities',
        ),
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='chunks_to_exclude',
        ),
    ]
