# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20160904_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='about',
        ),
    ]
