# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_remove_semester_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmilestone',
            name='excludedFilePatterns',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
        migrations.AddField(
            model_name='submitmilestone',
            name='includedFilePatterns',
            field=models.CharField(blank=True, default=b'*.java *.c *.h *.cpp *.CC *.py', max_length=300),
        ),
        migrations.AddField(
            model_name='submitmilestone',
            name='restrictAccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitmilestone',
            name='runCheckstyle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submitmilestone',
            name='startingCodePath',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='submitmilestone',
            name='submittedCodePath',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='submitmilestone',
            name='suppressCheckstyleRegex',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
