# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20170125_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmilestone',
            name='startingCodePath',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='submittedCodePath',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
    ]
