# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20170125_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='excludedFilePatterns',
            new_name='excluded_file_patterns',
        ),
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='includedFilePatterns',
            new_name='included_file_patterns',
        ),
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='restrictAccess',
            new_name='restrict_access',
        ),
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='runCheckstyle',
            new_name='run_checkstyle',
        ),
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='startingCodePath',
            new_name='starting_code_path',
        ),
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='submittedCodePath',
            new_name='submitted_code_path',
        ),
        migrations.RenameField(
            model_name='submitmilestone',
            old_name='suppressCheckstyleRegex',
            new_name='suppress_checkstyle_regex',
        ),
    ]
