# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20170125_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmilestone',
            name='excluded_file_patterns',
            field=models.CharField(blank=True, default=b'', help_text=b'Filename patterns to exclude from upload, separated by whitespace', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='included_file_patterns',
            field=models.CharField(blank=True, default=b'*.java *.c *.h *.cpp *.CC *.py', help_text=b'Filename patterns to upload, separated by whitespace; e.g. *Foo*.java matches Foo.java and src/TheFool/Bar.java', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='restrict_access',
            field=models.BooleanField(default=False, help_text=b"If enabled, restrict who can view the students' chunks to the student authors and any assigned reviewers"),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='run_checkstyle',
            field=models.BooleanField(default=False, help_text=b"If enabled, runs Checkstyle on the students' Java code, and preloads its output as comments in Caesar"),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='starting_code_path',
            field=models.CharField(blank=True, default=b'', help_text=b'Folder containing starting code for the assignment.  Should contain one subfolder, under which is the starting code.', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='submitted_code_path',
            field=models.CharField(blank=True, default=b'', help_text=b'Folder containing student code for the assignment. Should contain subfolders named by student usernames: abc/, def/, ghi/, etc.', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='suppress_checkstyle_regex',
            field=models.CharField(blank=True, default=b'', help_text=b'Regex of checkstyle comments to suppress; separate multiple patterns by |', max_length=200),
        ),
    ]
