# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-26 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20170125_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='allow_retroactive_extensions',
            field=models.BooleanField(default=False),
        ),
    ]
