# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-26 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_milestone_allow_retroactive_extensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='allow_retroactive_extensions',
        ),
        migrations.AddField(
            model_name='milestone',
            name='allow_unextending_to_past',
            field=models.BooleanField(default=False, help_text=b"If enabled, then user can give back extension days even if it pushes their deadline back into the past. If disabled, then user's deadline must always be in the future after a change."),
        ),
    ]
