# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20170126_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmilestone',
            name='chunk_priorities',
        ),
    ]
