# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_submitmilestone_starting_code_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmilestone',
            name='reveal_date',
            field=models.DateTimeField(blank=True, help_text=b'When comments are revealed to code author', null=True),
        ),
    ]
