# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 18:49
from __future__ import unicode_literals

from django.db import migrations


def populate_reveal_date(apps, schema_editor):
    # We can't import the ReviewMilestone model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ReviewMilestone = apps.get_model("review", "ReviewMilestone")
    for reviewmilestone in ReviewMilestone.objects.all():
        reviewmilestone.reveal_date = reviewmilestone.duedate
        reviewmilestone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_reviewmilestone_reveal_date'),
    ]

    operations = [
        migrations.RunPython(populate_reveal_date),
    ]
