# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_populate_reviewmilestone_reveal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmilestone',
            name='reveal_date',
            field=models.DateTimeField(blank=True, help_text=b'When comments are revealed to code author. If blank, comments are always visible to author.', null=True),
        ),
    ]
