# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20170225_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together=set([('user', 'milestone')]),
        ),
    ]
