# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_auto_20170921_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='restrict_access',
            field=models.BooleanField(default=False, help_text=b"If enabled, restrict who can view the students' chunks to the student authors and any assigned reviewers. LAs and TAs will not be able to view submissions if this is enabled."),
        ),
    ]
