# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20180221_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='started',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'N', b'New'), (b'O', b'Opened'), (b'C', b'Completed'), (b'U', b'Unfinished')], default=b'N', max_length=1),
        ),
    ]
